### ISSUE TITLE
Not using Akka Persistence

### ISSUE THREAD

**Issue by petersondrew** [evendotnet/Even#43]
I'm the readme you mention that Akka persistence was not suitable, would you be able to expand on that a little? I'm considering an event sourced application using Akka persistence and was wondering what pitfalls there were, and how even overcomes or sidesteps them?

Thanks!

**Comment by nvivo** [comment]
Hi @petersondrew,

There is nothing wrong with Akka Persistence. It's only that its actor centric while Even (like other event sourcing frameworks) is application centric. A poor analogy would be having multiple independent databases in a SQL database vs having a a single database with multiple tables and relations between them. 

Another way to put it is that Akka Persistence is not a framework, it's a tool that akka provides for the very specific task of persisting actor state. It doesn't try to be anything else. It's simple and it works for that task.

There is no right or wrong, but depending on what you want to do, one is more suitable than the other. I'd say that Akka persistence works well if you're writing backend services and want to persist actor state between app restarts, and for most services, that is enough. 

It's not suitable for more business oriented stuff, like persisting user history, knowing what was purchased, what was paid, when products arrived, and what happened before what. Things are going to get very tricky with Akka Persistence due to this lack of relation between events and actors. It would be like trying to build an entire building using only with a hammer. Nothing wrong with the hammer, it's just not enough for that task.
